### ISSUE TITLE
Ardrone-ffmpeg to syphon (rtsp client) freezing in full screen

### ISSUE THREAD

**Issue by pagaille** [eighteight/CinderEight#1]
Hi,
I'm using your ardrone-ffmpeg and encounter some problems with it, maybe you could help me.
I set up an RTSP server streaming a raspberry pi camera images. I use QLab as Syphon client to receive the pictures in order to use it in a live theatre.
I'm sure you never thought your app would be used for such a project, did you ? :-)
My problem is that it works perfectly, except when I put Qlab in full screen : after 40 seconds or alike the images freezes. If I close Qlab I see that the video goes live again in your app's preview screen.
I tried with another syphon source and Qlab had no problem with it.
I tried with another RTSP source (the bugs bunny one), same problem.
I tried to compile the GIT source but ran into endless problems using Xlab latest versions (something wrong regarding references to files)
Any idea what could cause that problem ?
I'm using High Sierra.
Txs

**Comment by pagaille** [comment]
Update : same behaviour in Isadora. May be linked to High Sierra (OSX 10.13) ?

**Comment by eighteight** [comment]
Hi, I presume you are on Mac.  Macs put the apps into sleep if their are not seeing on the screen

**Comment by pagaille** [comment]
HAAAAAA !

SPOT ON @eighteight !! 

`defaults write NSGlobalDomain NSAppSleepDisabled -bool YES` did the trick.

THANKS
